version: "3.9"
services:
  backend:
    build: .
    container_name: auth_service
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CHAVE_SECRETA: ${CHAVE_SECRETA}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always