spring.application.name=Auth-Service

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

CHAVE_SECRETA=${CHAVE_SECRETA}
